### PR TITLE
Added calendar popup

### PR DESCRIPTION
**Pull request by pkrishna05**

### CODE REVIEW

**Comment by Ryan-Ficklin** [comment]
Looks good to me. Most changes seem to be prettier changes, but the additions you made extend the code nicely to add the popout functionality.

**Comment by charpath** [comment]
Looks good to me, no comments here

**Comment by jfwoo** [comment]
no comments, looks good to me

**Comment by siddarthmaddhula** [comment]
No comments here, everything looks good.

**Pull request merged**
