### PR TITLE
Cypress testing

### PR DESCRIPTION
**Pull request by Ryan-Ficklin**
This adds cypress, and creates an end 2 end full test of the happy path of our app. 
The test follows this procedure:
Logs in using a new account called "cypresstest"
Creates two tasks
Checks to make sure the date with the higher priority is listed first
Checks to make sure both tasks are listed as events visible on the calendar
Edits one task to make it the higher priority, and checks the order again
Deletes the tasks, so that this test can be ran multiple times without side effects

### CODE REVIEW

**Comment by charpath** [comment]
Looks good to me, no comments

**Comment by jfwoo** [comment]
no comments, looks good to me

**Comment by siddarthmaddhula** [comment]
no comments here

**Comment by pkrishna05** [comment]
This looks good, no comments. Will merge the request.

**Pull request merged**
